### ISSUE TITLE
Something has happened to Nightscout Authentication between mid November and early April that breaks this deployment

### ISSUE THREAD

**Issue by alternateal** [joeyede/AutorunAutotune#4]
I had built my original autotune docker using a Nightscout build of the Master branch in November 15th 2020; following an update of the Master branch and re-deployment on April 8th 2021 - Autotune stopped working. Is there something in your build that needs changing - it tends to fail with this sort of failure

TypeError: opts.glucose.map is not a function

Stepping through the shell file manually made no difference

**Comment by joeyede** [comment]
I will need to look in to this.

**Comment by dicko72** [comment]
> I had built my original autotune docker using a Nightscout build of the Master branch in November 15th 2020; following an update of the Master branch and re-deployment on April 8th 2021 - Autotune stopped working. Is there something in your build that needs changing - it tends to fail with this sort of failure
> 
> TypeError: opts.glucose.map is not a function
> 
> Stepping through the shell file manually made no difference

@alternateal Did you resolve this issue?

**Comment by alternateal** [comment]
Honestly not had a chance to sit down and look at it logically - I am still using an old build of Nightscout to make it work. I suspect it is something in the Nightscout authentication, but again not spent enough time looking.

**Comment by dicko72** [comment]
> Honestly not had a chance to sit down and look at it logically - I am still using an old build of Nightscout to make it work. I suspect it is something in the Nightscout authentication, but again not spent enough time looking.

What version of NS are you on?

**Comment by joeyede** [comment]
I belive I found this issue.  
At some point authentication using the apikey stoped working and you must use the sha1 hash of your apikey so for e.g. if you currently have in Dockerfile:
ENV API_SECRET IloveAutoAutotune
replace it with:
ENV API_SECRET 7499FB74EE6A4FB035AD0A45848335CCEFDB90B6

One way to get the sha1 has would be to use: https://passwordsgenerator.net/sha1-hash-generator/
Sorry this took so long.  I know I'm not the only one who had a crazy year...

**Comment by joeyede** [comment]
tuned out this broke trigger profile which was expecting unhashed key.  Fixed script to hash it so you can continue to use unhashed key in Dockerfile if you update to lates version of these scripts
